### ISSUE TITLE
Angular+polymer binding doesn't work on FF and IE

### ISSUE THREAD

**Issue by PiotrekPaprocki** [PredixDev/predix-rmd-ref-app#15]
Hi

I have a problem described here https://forum.predix.io/questions/10852/angular-and-polymer-binding-doesnt-work-at-firefox.html

I have created a ticket and conclusion was to ask directly the team responsible for rmd-ref-app.

I am (and not only I) struggling with this problem. Are you familiar with it? Do you know how we can resolve this issue? What do you suggest?

Thanks,
Piotrek

**Comment by gstroup** [comment]
Sorry, we know there are issues with the UI code in FF and IE.  That UI was written last year, while the Predix UI framework was transitioning from angular to polymer.  We found some issues, and learned that it's not a good idea to use both polymer and angular 1 in the same project.  We're planning to rewrite the front end rmd-ref-app-ui project to use polymer only, after the new predix-seed is released.  In the meantime... I think you're stuck with Chrome for now.  Also, you might want to start looking at angular 2, since it works better with web components.

**Comment by turnerth** [comment]
closing since this was migrated to polymer 2
